OfficeBundle\Entity\Bien:
    type: entity
    table: Bien
    indexes:
        idType:
            columns:
                - idType
        idCommune:
            columns:
                - idCommune
        idProprietaire:
            columns:
                - idProprietaire
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombien:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: nomBien
        adresse:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        datedajout:
            type: datetime
            nullable: false
            column: dateDajout
        description:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        prixlocation:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: prixLocation
        negociation:
            type: integer
            nullable: false
            options:
                unsigned: false
        disponibilite:
            type: boolean
            nullable: false
        referencement:
            type: integer
            nullable: true
            options:
                unsigned: false
        referencier:
            type: integer
            nullable: true
            options:
                unsigned: false
        rterer:
            type: integer
            nullable: false
            options:
                unsigned: false
        errrr:
            type: integer
            nullable: false
            options:
                unsigned: false
        encore:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        idcommune:
            targetEntity: Commune
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCommune:
                    referencedColumnName: id
            orphanRemoval: false
        idproprietaire:
            targetEntity: Proprietaire
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idProprietaire:
                    referencedColumnName: id
            orphanRemoval: false
        idtype:
            targetEntity: Typedebien
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idType:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
