OfficeBundle\Entity\Client:
    type: entity
    table: Client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        structure:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        nomcomplet:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nomComplet
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        telephone:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
