OfficeBundle\Entity\Commune:
    type: entity
    table: Commune
    indexes:
        idDepartement:
            columns:
                - idDepartement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomcommune:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nomCommune
    manyToOne:
        iddepartement:
            targetEntity: Departement
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idDepartement:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
