OfficeBundle\Entity\Departement:
    type: entity
    table: Departement
    indexes:
        idRegion:
            columns:
                - idRegion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomdepartement:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nomDepartement
    manyToOne:
        idregion:
            targetEntity: Region
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idRegion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
