OfficeBundle\Entity\Image:
    type: entity
    table: Image
    indexes:
        idBien:
            columns:
                - idBien
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: blob
            nullable: false
            length: null
            options:
                fixed: false
    manyToOne:
        idbien:
            targetEntity: Bien
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idBien:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
