OfficeBundle\Entity\Region:
    type: entity
    table: Region
    indexes:
        idPays:
            columns:
                - idPays
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomregion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nomRegion
    manyToOne:
        idpays:
            targetEntity: Pays
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPays:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
