OfficeBundle\Entity\Typedebien:
    type: entity
    table: TypeDeBien
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomtype:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nomType
    lifecycleCallbacks: {  }
